baseURL = 'https://example.org/'
title = 'Fluxio'
theme = 'parsa'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[outputs]
  home = ["HTML", "RSS", "JSON"]


[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    contentDir = 'content/en'
  [languages.zh-cn]
    languageName = '简体中文'
    weight = 2
    contentDir = 'content/zh-cn'
  [languages.zh-tw]
    languageName = '繁體中文'
    weight = 3
    contentDir = 'content/zh-tw'

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Fluxio - Modern Tech News"
  author = "Fluxio Team"
  layout = "2"
  default_image = "images/placeholder.svg"
  og_image = "images/placeholder.svg"
  # Custom CSS for Glassmorphism
  custom_css = ["css/custom.css"]
  
  # Search
  search = true

  # Plugins (Copied from exampleSite, essential for theme function)
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"
  
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  link = "plugins/search/mark.js"
  [[params.plugins.js]]
  link = "plugins/search/search.js"

  # Virtual social profile (placeholder)
  [[params.social]]
  icon = "ti-github"
  link = "#"

  # Geo SEO (update to your actual location)
  [params.geo]
    region = "TW-TPE"
    placename = "Taipei"
    position = "25.0330;121.5654"
